on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-variant: ['BC', 'CS']
        racket-version: ['7.8', '7.9']
    name: Test on ${{ matrix.racket-variant }} Racket
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.3.1
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Install package and its dependencies
        run: make install
      - name: Check dependencies
        run: make check-deps
      - name: Run tests
        run: make test
