on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        racket-variant: ['BC', 'CS']
        racket-version: ['7.8', 'stable']
        experimental: [false]
        include:
          - racket-version: 'current'
            racket-variant: 'CS'
            experimental: true
    name: Test on Racket ${{ matrix.racket-variant }} ${{ matrix.racket-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.3.1
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Install package and its dependencies
        run: make install
      - name: Check dependencies
        run: make check-deps
      - name: Run tests
        run: make test
  coverage:
    needs: test
    runs-on: ubuntu-latest
    environment: test-env
    name: Report Coverage
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.3.1
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: 'stable'
      - name: Install package and its dependencies
        run: make install
      - name: Report coverage
        run: make cover-coveralls
